version: '3.5'
services:
    provider-ctk-tnt:
        environment:
            - API_ROOT_URI=http://192.168.178.94:9090 # change this to host IP
            - CALLBACK_PORT=9999
            - CALLBACK_URI=http://localhost
            - CALLBACK_WAIT=3000
            - TEST_SUITE=TNT-TestSuite.xml
            - CONFIG_DATA=config/v2/config.json
            - TEST_DATA=config/v2/testdata.json
        container_name: provider-ctk
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - C:\workspace\ctk\reports:/ctk/reports
            - C:\workspace\ctk\testdata:/ctk/testdata
        ports:
           # - 9999:9999
            - 9000:9000
         #   - 5005:5005