version: '3.5'
services:
    ctk:
        environment:
            - API_ROOT_URI=http://192.168.178.38:9090/v2
            - CALLBACK_PORT=9092
            - CALLBACK_URI=http://192.168.178.38:9092/v2
            - CALLBACK_WAIT=20000
        container_name: test
        build:
            .
        volumes:
            - C:\workspace\abc\ctk\reports:/ctk/reports
        ports:
            - $CALLBACK_PORT:$CALLBACK_PORT